image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - build
  - test
  - archive

build:
  artifacts:
    expire_in: "30 minutes"
    name: "BizHawk_tempbuild_$CI_COMMIT_REF_SLUG"
    paths:
      - output
      - test_output
  script:
    - Dist/BuildRelease.sh
  stage: build

check_style:
  script:
    - Dist/BuildRelease.sh -p:MachineRunAnalyzersDuringBuild=true
  stage: test

run_tests:
  artifacts:
    paths:
      - test_output/*.coverage.xml
    reports:
      junit:
        - test_output/*.coverage.xml
  script:
    - Dist/BuildTestRelease.sh
  stage: test

create_archive:
  artifacts:
    expire_in: "1 month"
    name: "BizHawk_devbuild_$CI_COMMIT_REF_SLUG"
    paths:
      - output
  only:
    - master
  script:
    - ''
  stage: archive

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - packages
